ignore configure_optimizers warning
YosefLab/scvi-tools pull request #1064
Opened 2021-05-15 18:49 UTC by mjayasur

closes #1057

2021-05-15 23:29 UTC, wukathy approved these changes
lgtm

2021-05-16 01:50 UTC, adamgayoso requested changes

2021-05-16 01:50 UTC, adamgayoso commented on scvi/train/_trainer.py
> +            warnings.filterwarnings(
let's only filter it if the model passed to fit is an instance of:

https://github.com/YosefLab/scvi-tools/blob/a9da914764d311ff18b4b557b78d9550a3b940af/scvi/train/_trainingplans.py#L581

See the pylit API here, model should be the first arg.

https://pytorch-lightning.readthedocs.io/en/latest/common/trainer.html#fit

2021-05-20 02:20 UTC, adamgayoso requested changes

2021-05-20 02:20 UTC, adamgayoso commented on scvi/train/_trainer.py
> +import scvi.train
import needs to be fixed :)

2021-05-24 16:49 UTC, merged