extend history when train method run multiple times
YosefLab/scvi-tools pull request #1091
Opened 2021-06-21 20:33 UTC by adamgayoso

Fixes #1065

2021-06-30 07:01 UTC, galenxing commented on scvi/train/_trainrunner.py
> +                    self.model.history_ = self.trainer.logger.history
Let's move the warning message into the if statement, so it only warns if it actually does replace the old history. Also, I'm pretty sure every model has a `history_` attribute. It's in the init of BaseModelClass.

2021-06-30 07:02 UTC, galenxing requested changes

2021-06-30 07:02 UTC, galenxing commented on scvi/train/_trainrunner.py
> +                    self.model.history_ = self.trainer.logger.history
Let's move the warning message into the if statement, so it only warns if it actually does replace the old history. Also, I'm pretty sure every model has a history_ attribute. It's in the init of BaseModelClass.

2021-07-02 18:27 UTC, adamgayoso commented on scvi/train/_trainrunner.py
> +                self.model.history_ = self.trainer.logger.history
```suggestion
            self.model.history_ = self.trainer.logger.history
```

2021-07-13 18:46 UTC, galenxing approved these changes

2021-07-13 18:54 UTC, merged