Bug fix in pyromixin for posterior sampling
YosefLab/scvi-tools pull request #1158
Opened 2021-09-14 00:31 UTC by vitkl

The method `._get_obs_plate_sites()` should discard observed variables (unless requested otherwise) and plates. Current code always performs posterior sampling even if unobserved local variables do not exist in the model, e.i. code never enters this statement:
```
if len(obs_plate_sites) == 0:
    # if no local variables - don't sample
    break
```

This PR addresses the issue by adding a check for observed and plates.

2021-09-14 02:29 UTC, vitkl commented
@adamgayoso please have a look at this

2021-09-14 05:16 UTC, adamgayoso requested changes
LGTM outside of the small request for docstring

2021-09-14 05:16 UTC, adamgayoso commented on scvi/model/base/_pyromixin.py
> +    def _get_obs_plate_sites(self, args, kwargs, sample_observed):
can you document this function and add relevant typing?

2021-09-21 20:47 UTC, vitkl commented
I think this is done now.

2021-09-22 04:56 UTC, adamgayoso requested changes

2021-09-22 04:56 UTC, adamgayoso commented on scvi/model/base/_pyromixin.py
> +        kwargs: Optional[dict],
usually optional has a None default. Don't believe this is the case here?

2021-09-22 11:14 UTC, vitkl commented
Yes, you are right actually - these arguments are not optional and don't
have default values. I will change this.

On Wed, 22 Sep 2021, 05:56 Adam Gayoso, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In scvi/model/base/_pyromixin.py
> <https://github.com/YosefLab/scvi-tools/pull/1158#discussion_r713590098>:
>
> > +        args: Optional[list],
> +        kwargs: Optional[dict],
>
> usually optional has a None default. Don't believe this is the case here?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/YosefLab/scvi-tools/pull/1158#pullrequestreview-760451219>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFMFTVYDBGGSSQDKZ5B3L6TUDFOXJANCNFSM5D663UCQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-01 00:33 UTC, adamgayoso commented on scvi/model/base/_pyromixin.py
> +        kwargs: Optional[dict],
```suggestion
        args: list,
        kwargs: dict,
```

2021-10-01 00:59 UTC, adamgayoso approved these changes

2021-10-01 01:00 UTC, merged