Adapt TotalVI to new setup
YosefLab/scvi-tools pull request #1298
Opened 2022-01-04 02:17 UTC by jjhong922

2022-01-10 16:20 UTC, adamgayoso requested changes
need to do another review, but looks good

2022-01-10 16:20 UTC, adamgayoso commented on scvi/data/anndata/fields/_obsm_field.py
> +            logger.info("Generating sequential protein names")
should be generic

2022-01-10 16:20 UTC, adamgayoso commented on scvi/data/anndata/fields/_obsm_field.py
> +                f"Using protein names from adata.uns['{self.colnames_uns_key}']"
should be generic

2022-01-10 16:20 UTC, adamgayoso commented on scvi/data/anndata/fields/_obsm_field.py
> +        )
should we actually check if the column names are the same?

2022-01-14 18:04 UTC, jjhong922 commented on scvi/data/anndata/fields/_obsm_field.py
> +    An AnnDataField for an .obsm field in the AnnData data structure.
AnnDataField doesn't exist only the concept of one (child of a BaseAnnDataField). Do you think I should just link this? Or perhaps ``Type[~scvi...AnnDataField]``.

2022-01-15 00:21 UTC, jjhong922 commented on scvi/data/anndata/fields/_obsm_field.py
> +    An AnnDataField for an .obsm field in the AnnData data structure.
Leaving this for now, can change in a later PR.

2022-01-15 02:00 UTC, merged