Cleanup Manager register reference with AttrDict implementation
YosefLab/scvi-tools pull request #1307
Opened 2022-01-19 02:19 UTC by jjhong922

Makes data_registry, state_registry, and summary_stats properties return attrdicts which allow users to reference dictionary keys using attribute notation. This cleans up verbose references to field constants without importing the original field class.

2022-01-31 04:35 UTC, adamgayoso commented on scvi/utils/_attrdict.py
> +class attrdict(dict):
we will probably have to ignore this on codacy

2022-01-31 04:36 UTC, adamgayoso commented on scvi/utils/_attrdict.py
> +    Based off of https://stackoverflow.com/questions/38034377/object-like-attribute-access-for-nested-dictionary.
Put in Notes section like

```
Notes
-----
...
```

2022-01-31 05:16 UTC, adamgayoso requested changes

2022-01-31 05:16 UTC, adamgayoso commented on scvi/utils/__init__.py
> +__all__ = ["track", "setup_anndata_dsp", "attrdict"]
we need to add `attrdict` to the docs page

2022-01-31 05:16 UTC, adamgayoso commented on scvi/utils/_attrdict.py
> +class attrdict(dict):
also should we overwrite the repr? To better communicate there that it's an attrdict and not a dict?

2022-01-31 05:16 UTC, adamgayoso commented on scvi/utils/_attrdict.py
> +class attrdict(dict):
would help devs see what they can do with it

2022-02-01 20:10 UTC, jjhong922 commented on scvi/utils/_attrdict.py
> +class attrdict(dict):
the check passed on codacy, did you ignore something? And yes I'll overwrite the repr can just append something to the front of it

2022-02-02 21:21 UTC, merged