Stereoscope lit
YosefLab/scvi-tools pull request #864
Opened 2020-12-03 17:02 UTC by romain-lopez

These changes make it possible to run Stereoscope with the new API. It will require some improvements before merging. So far, Adam and I have flagged:
+ documentation (overall)
+ math in documentation can be formated
+ using register buffer instead of parameter with no grad
+ add reference in documentation
+ save / load in unit test? 

Please let me know if you find some other things.

2020-12-03 17:03 UTC, romain-lopez commented
Ah! and we might want to look into this trainer behavior for no validation set and see if we can do something nicer. I don't like having to give the train_set twice to the pytorch lightning task

2020-12-07 17:20 UTC, adamgayoso requested changes

2020-12-07 17:20 UTC, adamgayoso commented on scvi/external/stereoscope/_module.py
> +        return None
raise NotImplementedError

2020-12-07 17:20 UTC, adamgayoso commented on scvi/model/base/_base_model.py
> +            self.trainer.fit(self._pl_task, train_dl, train_dl)
I think what you can do is just pass the train_dl and that's it, no val loop this way.

2020-12-07 17:20 UTC, adamgayoso commented on tests/external/test_stereoscope.py
> +import scvi
this needs to be a proper test, see the examples in test_models.py, just needs to be in function called `test_stereoscope()`.

You should also use the synthetic iid dataset for simplicity.

2020-12-07 17:20 UTC, adamgayoso commented on tests/external/test_stereoscope.py
> +print(model.history)
no need for print, could just smoke test it.

2020-12-07 17:20 UTC, adamgayoso commented on tests/external/test_stereoscope.py
> +from scvi.external.stereoscope import RNAStereoscope, SpatialStereoscope
you shouldn't need `scvi.external.stereoscope` -- it should be just `scvi.external`.

2020-12-07 17:20 UTC, adamgayoso commented on scvi/external/stereoscope/_model.py
> +
need docstring for model kwargs -- see the scvi.py code for how to link to the proper model class.

2020-12-07 17:20 UTC, adamgayoso commented on scvi/external/stereoscope/_model.py
> +
need model kwargs here too

2020-12-07 17:20 UTC, adamgayoso commented on scvi/external/stereoscope/_model.py
> +    >>> stereo = scvi.external.stereoscope.SpatialStereoscope(st_adata, sc_params)
example shouldn't need stereoscope -- should be `scvi.external.SpatialStereoscope`, same for RNA

2020-12-07 17:20 UTC, adamgayoso commented on scvi/external/stereoscope/_module.py
> +from scvi.compose import AbstractVAE, auto_move_data, SCVILoss
the imports should be sorted. https://pypi.org/project/isort/

just be sure to isort only the stereoscope directory

2020-12-07 17:20 UTC, adamgayoso commented on scvi/external/stereoscope/_module.py
> +        #####
this math could actually go in the class docstring, if you look at the numpydoc specification, there's a notes section and you can do block math latex.

2020-12-07 17:20 UTC, adamgayoso commented on scvi/external/stereoscope/_module.py
> +        #####
this applies to all the math if you wish.

2020-12-07 17:20 UTC, adamgayoso commented on scvi/external/stereoscope/_model.py
> +    >>> stereo = scvi.external.stereoscope.RNAStereoscope(sc_adata)
no `stereoscope` needed here.

2020-12-07 17:20 UTC, adamgayoso commented on scvi/external/stereoscope/_module.py
> +        # x_sg \sim NB(softplus(\beta_g) * \sum_{z=1}^Z softplus(v_sz) * softplus(W)_gz + \gamma_s \eta_g, exp(px_r))
math could be moved to docstring, see other comment

2020-12-08 15:00 UTC, romain-lopez commented
Alright! I think this is good to go, and should have the minimal functionalities we discussed! Let me know if you have any other comments, and generally, if you see some obvious doc changes you'd like to see implemented please go ahead!

2020-12-08 15:03 UTC, romain-lopez commented
checked pytest, flake8, black. not sure what codacy wants from me :)

2020-12-08 15:58 UTC, adamgayoso requested changes

2020-12-08 15:58 UTC, adamgayoso commented on tests/external/test_stereoscope.py
> +def test_scvi(save_path):
```suggestion
def test_stereoscope(save_path):
```

2020-12-09 00:14 UTC, adamgayoso requested changes

2020-12-09 00:14 UTC, adamgayoso commented on scvi/external/stereoscope/_model.py
> +    def get_params(self):
need some sort of documentation here and typing

2020-12-09 00:14 UTC, adamgayoso commented on scvi/external/stereoscope/_model.py
> +        params: np.ndarray,
need to add this to the docstring and add typing.

2020-12-09 00:14 UTC, adamgayoso commented on scvi/external/stereoscope/_module.py
> +    def get_params(self) -> torch.Tensor:
I'd add an `@torch.no_grad()` decorator here and then you don't need detach.

2020-12-09 00:14 UTC, adamgayoso commented on scvi/external/stereoscope/_module.py
> +    def get_proportions(self, keep_noise=False) -> torch.Tensor:
same with torch no grad decorator

2020-12-10 11:32 UTC, romain-lopez commented
added those!

2020-12-10 12:40 UTC, romain-lopez commented
Actually, one more thing is how we should incorportate the registration of the ind_x into the anndata at load time with mininal changes. Any suggestions?

2020-12-31 18:11 UTC, closed without merging