WIP: train method
YosefLab/scvi-tools pull request #936
Opened 2021-02-19 00:55 UTC by galenxing

2021-02-22 16:33 UTC, adamgayoso requested changes

2021-02-22 16:33 UTC, adamgayoso commented on scvi/model/_scanvi.py
> +from scvi import _CONSTANTS  # , settings
flag

2021-02-22 16:33 UTC, adamgayoso commented on scvi/dataloaders/_data_splitting.py
> +        if self.train_size > 1.0 or self.train_size <= 0.0:
let's also check that val_size is valid (in 0 to 1)

2021-02-22 16:33 UTC, adamgayoso commented on scvi/dataloaders/_data_splitting.py
> +        if self.train_size > 1.0 or self.train_size <= 0.0:
apparently it works to give val size a large integer right now

2021-02-22 17:19 UTC, adamgayoso commented on scvi/external/solo/_model.py
> +    def _set_training_plan(self, plan_class=None, plan_kwargs=None):
Remove

2021-02-23 01:46 UTC, adamgayoso requested changes

2021-02-23 01:46 UTC, adamgayoso commented on scvi/model/_scanvi.py
> +        # if we have labeled cells, we want to subsample labels each epoch
can be removed right?

2021-02-23 01:46 UTC, adamgayoso commented on scvi/model/_scanvi.py
> +        # if we have labeled cells, we want to subsample labels each epoch
referring to commented out code above

2021-02-23 02:33 UTC, galenxing commented on scvi/model/_scanvi.py
> +        # if we have labeled cells, we want to subsample labels each epoch
yea im removing in the gpu pr

2021-02-23 06:09 UTC, adamgayoso requested changes

2021-02-23 06:09 UTC, adamgayoso commented on scvi/dataloaders/_data_splitting.py
> +    """
add examples

2021-02-23 06:09 UTC, adamgayoso commented on scvi/external/solo/_model.py
> +class SOLO(UnsupervisedTrainingMixin, BaseModelClass):
why does it need the mixin?

2021-02-23 06:09 UTC, adamgayoso commented on scvi/external/solo/_model.py
> +class SOLO(UnsupervisedTrainingMixin, BaseModelClass):
it should only need it if you call super below, which seems like a fine option to me

2021-02-23 06:09 UTC, adamgayoso commented on scvi/model/base/_training_mixin.py
> +            Keyword args for model-specific Pytorch Lightning task. Keyword arguments passed to
```suggestion
            Keyword args for :class:`~scvi.lightning.TrainingPlan`. Keyword arguments passed to
```

2021-02-23 06:09 UTC, adamgayoso commented on scvi/model/base/_trainrunner.py
> +    """
examples

2021-02-23 16:17 UTC, adamgayoso commented on scvi/dataloaders/_data_splitting.py
> +            )
use RandomState like in the main splitter

2021-02-23 16:18 UTC, adamgayoso commented on scvi/dataloaders/_data_splitting.py
> +            )
randomstate

2021-02-23 21:10 UTC, adamgayoso approved these changes
LGTM

2021-02-23 21:10 UTC, merged